spring:
  application:
    name: untappd-cqrs
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/untappd-cqrs
    username: postgres
    password: postgres

  management.security.enabled: false

debug: true

server:
  port: 8080